import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
export const inter = Inter({ subsets: ['latin'], display: 'swap' });
export const metadata: Metadata = {
  title: 'PassLimits',
  description: 'Generated by PassLimits',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${inter.className}`}>
      <body>{children}</body>
    </html>
  );
}
